apiVersion: v1
kind: Service
metadata:
  name: linkspan-client
  namespace: linkspan
  labels:
    app.kubernetes.io/name: linkspan
    app.kubernetes.io/component: client
spec:
  selector:
    app: linkspan-client
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
