apiVersion: v1
kind: Service
metadata:
  name: linkspan-signaling
  namespace: linkspan
  labels:
    app.kubernetes.io/name: linkspan
    app.kubernetes.io/component: signaling
spec:
  selector:
    app: linkspan-signaling
  ports:
    - name: http
      port: 10000
      targetPort: 10000
      protocol: TCP
  type: ClusterIP
